# Generated by Django 4.0.3 on 2022-03-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plaintiff_name', models.CharField(blank=True, max_length=50, verbose_name='원고')),
                ('defendant_name', models.CharField(blank=True, max_length=50, verbose_name='피고')),
                ('court_datetime', models.DateTimeField(blank=True, verbose_name='다음 기일')),
                ('court_location', models.CharField(blank=True, choices=[('seoul', '서울'), ('busan', '부산'), ('daejeon', '대전'), ('daegu', '대구')], max_length=20, verbose_name='장소')),
                ('case_num', models.CharField(blank=True, max_length=20, verbose_name='사건번호')),
                ('case_name', models.CharField(blank=True, max_length=20, verbose_name='사건명')),
                ('casedate_type', models.CharField(choices=[('arguedate', '변론기일'), ('crim_arguedate', '공판기일'), ('decisiondate', '선고기일'), ('settledate', '조정기일'), ('crim_arguedate', '공판기일'), ('questiondate', '심문기일'), ('etcdate', '기타')], max_length=20, verbose_name='기일구분')),
                ('case_attorney', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당변호사')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
