# Generated by Django 4.0.3 on 2022-04-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_court_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_location',
            field=models.CharField(blank=True, choices=[('서울', '서울'), ('부산', '부산'), ('대전', '대전'), ('대구', '대구')], max_length=20, verbose_name='관할'),
        ),
    ]
