# Generated by Django 4.0.3 on 2022-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_court_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='casedate_type',
            field=models.CharField(choices=[('변론기일', '변론기일'), ('공판기일', '공판기일'), ('선고기일', '선고기일'), ('조정기일', '조정기일'), ('공판기일', '공판기일'), ('심문기일', '심문기일'), ('기타', '기타')], max_length=20, verbose_name='기일구분'),
        ),
    ]
