# Generated by Django 4.0.3 on 2022-04-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_casedate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
